apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dhcp-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "ens18",
    "mode": "bridge",
    "ipam": {
      "type": "dhcp"
      "type": "host-local",
    }
  }'
